FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Marvel-World API

Marvel-World is a simple API allowing users to view comics, characters, stories, series, events, and the creators behind them.


# Group Characters
Character related resources from the Marvel-World API.

## Character Collection [/characters]
A list of all the characters available. This list contains the characters names,
along with their unique ID's. The unique ID can be used to look up a certain character.
### Get all characters [GET /characters]
+ Response 200 (application/json)

    + Body
    
            { 
                "Characters": [
                  {
                    "id": "1",
                    "name": "Spider Man"
                  },
                  {
                    "ID": "2",
                    "Name": "Hulk"
                  },
                  {  
                    "ID": "3",
                    "Name": "Wolverine"
                  },
                  {
                    "ID": "4",
                    "Name": "Captain America"
                  }
                ]
            }

## Character [/characters/{character_ID}]


# Group Comics
Comic related resources of the Marvel-World API.

## Comic Book Collection [/comics/]
A collection of all the comic books that are available. Each comic has an associated ID with it.

### Get all comics [GET]
+ Response 200 (application/json)

    + Body
    
            {
                "Comics": [
                  {
                    "ID:": "1",
                    "Name:": "The Amazing Spider Man"
                  },
                  {
                    "ID:": "2",
                    "Name:": "The Incredible Hulk"
                  },
                  {
                    "ID:": "3",
                    "Name": "




## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }