FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Marvel-World API

Marvel-World is a simple API allowing users to view comics, characters, stories, series, events, and the creators behind them.


# Group Characters
Character related resources from the Marvel-World API.

## Character Collection [/characters]
A list of all the characters available. This list contains the characters names,
along with their unique ID's. The unique ID can be used to look up a certain character.
### Get all characters [GET]
+ Response 200 (application/json)

    + Body
    
            { 
                "Characters": [
                  {
                    "id": "1",
                    "name": "Spider Man"
                  },
                  {
                    "ID": "2",
                    "Name": "Hulk"
                  },
                  {  
                    "ID": "3",
                    "Name": "Wolverine"
                  },
                  {
                    "ID": "4",
                    "Name": "Captain America"
                  }
                ]
            }

## Character [/characters/{character_ID}]
Gets information on a certain character in the Marvel World database. Each character has an associated character ID. To a retrieve information for a certain character, 

### Get Certain Character [GET]
+ Response 200 (application/json)

    + Body
    
            {
                
                
            }


# Group Comics
Comic related resources of the Marvel-World API.

## Comic Book Collection [/comics]
A collection of all the comic books that are available. Each comic has an associated ID with it.

### Get all comics [GET]
+ Response 200 (application/json)

    + Body
    
            {
                "Comics": [
                  {
                    "ID:": "1",
                    "Name:": "The Amazing Spider Man"
                  },
                  {
                    "ID:": "2",
                    "Name:": "The Incredible Hulk"
                  },
                  {
                    "ID:": "3",
                    "Name": "Wolverine"
                  },
                  {
                    "ID:": "4",
                    "Name": "Captain America"
                  }
                ]
            }

## Comic Book [/comics/{comic_id}]
Retrieves information for a specific comic book, depending on the ID. 

### Get One Comic [GET /comics/{comic_ID}]
+ Response 200 (application/json)

    + Body 
    
            {
            
            }


# Group Series
All event related resources from the Marvel-World API.

## Event Collection [/series]
A collection of all the events that are available. Each event has an id associated with it.

### Get All Events [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "Series": [
                  {
                    "id:": "1",
                    "Title:": ""
                  },
                  {
                    "id:": "2",
                    "Title:": ""
                  },
                  {
                    "id:": "3",
                    "Title:": ""
                  },
                    "id:": "4",
                    "Title:": ""
                  }
                ]
            }
            



# Group Events
All event related resources from the Marvel-World API.

## Event Collection [/events]
A collection of all the events that are available. Each event has an id associated with it.

### Get All Events [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "Events": [
                  {
                    "id:": "1",
                    "Title:": ""
                  },
                  {
                    "id:": "2",
                    "Title:": ""
                  },
                  {
                    "id:": "3",
                    "Title:": ""
                  },
                    "id:": "4",
                    "Title:": ""
                  }
                ]
            }